name: Branch Protection Rules
description: Rules to protect the main branch
enforcement: active
bypass-actors:
  - actor: cormac321-lang
    bypass-mode: always
rules:
  - name: Require status checks to pass before merging
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
          - build
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_review_approvals: true
        require_code_owner_reviews: false
      required_workflows:
        - status-checks
targets:
  branches:
    - main 